### ISSUE TITLE
Lack of session close

### ISSUE THREAD

**Issue by WalterInSH** [cloudera/kudu-examples#25]
In Java sample, do we need to close the session?
Without closing the session, an OutOfMemory occurred.

```
        <dependency>
            <groupId>org.apache.kudu</groupId>
            <artifactId>kudu-client</artifactId>
            <version>1.0.1</version>
        </dependency>
```

**Comment by adembo** [comment]
Yes, it's important to close KuduSessions, otherwise they'll linger in the KuduClient instance and will only be destroyed when the KuduClient itself is destroyed.

**Comment by adembo** [comment]
Oh, you were asking about the java-sample code (I misunderstood and thought you were asking about session in general).

I don't think closing is terribly important there, because so little work is done with the KuduClient instance before it becomes orphaned and is GC'ed.

If you're seeing OutOfMemoryErrors, could you reopen and provide some more information?
